version: '3.8'
services:  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.1.3 #optional
    volumes:
      - jellyfin:/config
      - ./data:/data:rw
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - exposable
  
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
    volumes:
      - jackett:/config
      - ./data/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - exposable

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
      - ./data:/data:rw
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - exposable
  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - radarr:/config
      - ./data:/data:z
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - exposable

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - bazarr:/config
      - ./data:/data:z
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - exposable

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - ./data:/data:z
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - exposable

volumes:
  jellyfin:
  sonarr:
  radarr:
  bazaar:
  jackett:
  qbittorent:
  

networks:
  exposable:
    external: true

